[package]
name = "archive-config"
version = "0.1.0"
edition = "2021"

[lib]
name = "archive_config"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.5.0"
log = "0.4.22"
serde = "1.0.215"
toml = "0.8.19"
